export const CHAPTERS_BY_EXAM_SUBJECT = {
    "10th CBSE Board": {
        "Psychology": [
            "1. What is Psychology?",
            "2. Methods of Enquiry in Psychology",
            "3. The Bases of Human Behaviour",
            "4. Human Development",
            "5. Sensory, Attentional and Perceptual Processes",
            "6. Learning",
            "7. Human Memory",
            "8. Thinking",
            "9. Motivation and Emotion"
        ],
        "Mathematics": [
            "1. Real Numbers",
            "2. Polynomials",
            "3. Pair of Linear Equations in Two Variables",
            "4. Quadratic Equations",
            "5. Arithmetic Progressions",
            "6. Triangles",
            "7. Coordinate Geometry",
            "8. Introduction to Trigonometry",
            "9. Some Applications of Trigonometry",
            "10. Circles",
            "11. Constructions",
            "12. Areas Related to Circles",
            "13. Surface Areas and Volumes",
            "14. Statistics",
            "15. Probability"
        ],
        "Physics": [
            "1. Light - Reflection and Refraction",
            "2. The Human Eye and the Colourful World",
            "3. Electricity",
            "4. Magnetic Effects of Electric Current",
            "5. Sources of Energy",
            "6. Our Environment",
            "7. Management of Natural Resources"
        ],
        "Chemistry": [
            "1. Chemical Reactions and Equations",
            "2. Acids, Bases and Salts",
            "3. Metals and Non-metals",
            "4. Carbon and its Compounds",
            "5. Periodic Classification of Elements"
        ],
        "Biology": [
            "1. Life Processes",
            "2. Control and Coordination",
            "3. How do Organisms Reproduce?",
            "4. Heredity and Evolution",
            "5. Our Environment",
            "6. Management of Natural Resources"
        ],
        "English": [
            "1. A Letter to God",
            "2. Nelson Mandela: Long Walk to Freedom",
            "3. Two Stories About Flying",
            "4. From the Diary of Anne Frank",
            "5. The Hundred Dresses I",
            "6. The Hundred Dresses II",
            "7. Glimpses of India",
            "8. Mijbil the Otter",
            "9. Madam Rides the Bus",
            "10. The Sermon at Benares",
            "11. The Proposal"
        ],
        "Hindi": [
            "1. Kshitij",
            "2. Kritika",
            "3. Sparsh",
            "4. Sanchayan"
        ],
        "History": [
            "1. The Rise of Nationalism in Europe",
            "2. Nationalism in India",
            "3. The Making of a Global World",
            "4. The Age of Industrialisation",
            "5. Print Culture and the Modern World",
            "6. Work, Life and Leisure"
        ],
        "Geography": [
            "1. Resources and Development",
            "2. Forest and Wildlife Resources",
            "3. Water Resources",
            "4. Agriculture",
            "5. Minerals and Energy Resources",
            "6. Manufacturing Industries",
            "7. Lifelines of National Economy"
        ],
        "Political Science": [
            "1. Power Sharing",
            "2. Federalism",
            "3. Democracy and Diversity",
            "4. Gender, Religion and Caste",
            "5. Popular Struggles and Movements",
            "6. Political Parties",
            "7. Outcomes of Democracy"
        ],
        "Economics": [
            "1. Development",
            "2. Sectors of the Indian Economy",
            "3. Money and Credit",
            "4. Globalisation and the Indian Economy",
            "5. Consumer Rights"
        ],
        "Computer Science": [
            "1. Internet Basics",
            "2. Internet Services",
            "3. Introduction to HTML",
            "4. Introduction to CSS",
            "5. More on HTML",
            "6. More on CSS",
            "7. Cyber Ethics"
        ]
    },
    "12th CBSE Board": {
        "Psychology": [
            "1. Variations in Psychological Attributes",
            "2. Self and Personality",
            "3. Meeting Life Challenges",
            "4. Psychological Disorders",
            "5. Therapeutic Approaches and Counselling",
            "6. Attitude and Social Cognition",
            "7. Social Influence and Group Processes",
            "8. Psychology and Life",
            "9. Developing Psychological Skills"
        ],
        "Mathematics": [
            "1. Relations and Functions",
            "2. Inverse Trigonometric Functions",
            "3. Matrices",
            "4. Determinants",
            "5. Continuity and Differentiability",
            "6. Application of Derivatives",
            "7. Integrals",
            "8. Application of Integrals",
            "9. Differential Equations",
            "10. Vector Algebra",
            "11. Three Dimensional Geometry",
            "12. Linear Programming",
            "13. Probability"
        ],
        "Physics": [
            "1. Electric Charges and Fields",
            "2. Electrostatic Potential and Capacitance",
            "3. Current Electricity",
            "4. Moving Charges and Magnetism",
            "5. Magnetism and Matter",
            "6. Electromagnetic Induction",
            "7. Alternating Current",
            "8. Electromagnetic Waves",
            "9. Ray Optics and Optical Instruments",
            "10. Wave Optics",
            "11. Dual Nature of Radiation and Matter",
            "12. Atoms",
            "13. Nuclei",
            "14. Semiconductor Electronics: Materials, Devices and Simple Circuits"
        ],
        "Chemistry": [
            "1. The Solid State",
            "2. Solutions",
            "3. Electrochemistry",
            "4. Chemical Kinetics",
            "5. Surface Chemistry",
            "6. General Principles and Processes of Isolation of Elements",
            "7. The p-Block Elements",
            "8. The d- and f-Block Elements",
            "9. Coordination Compounds",
            "10. Haloalkanes and Haloarenes",
            "11. Alcohols, Phenols and Ethers",
            "12. Aldehydes, Ketones and Carboxylic Acids",
            "13. Amines",
            "14. Biomolecules",
            "15. Polymers",
            "16. Chemistry in Everyday Life"
        ],
        "Biology": [
            "1. Reproduction in Organisms",
            "2. Sexual Reproduction in Flowering Plants",
            "3. Human Reproduction",
            "4. Reproductive Health",
            "5. Principles of Inheritance and Variation",
            "6. Molecular Basis of Inheritance",
            "7. Evolution",
            "8. Human Health and Disease",
            "9. Strategies for Enhancement in Food Production",
            "10. Microbes in Human Welfare",
            "11. Biotechnology: Principles and Processes",
            "12. Biotechnology and its Applications",
            "13. Organisms and Populations",
            "14. Ecosystem",
            "15. Biodiversity and Conservation",
            "16. Environmental Issues"
        ],
        "English": [
            "1. The Last Lesson",
            "2. Lost Spring",
            "3. Deep Water",
            "4. The Rattrap",
            "5. Indigo",
            "6. Poets and Pancakes",
            "7. The Interview",
            "8. Going Places",
            "9. My Mother at Sixty-six",
            "10. An Elementary School Classroom in a Slum",
            "11. Keeping Quiet",
            "12. A Thing of Beauty",
            "13. A Roadside Stand",
            "14. Aunt Jennifer's Tigers"
        ],
        "Hindi": [
            "1. Aroh",
            "2. Vitan",
            "3. Antral",
            "4. Antrbhag"
        ],
        "History": [
            "1. The Story of the First Cities: Harappan Archaeology",
            "2. Kings, Farmers and Towns: Early States and Economies",
            "3. Kinship, Caste and Class: Early Societies",
            "4. Thinkers, Beliefs and Buildings: Cultural Developments",
            "5. Through the Eyes of Travellers: Perceptions of Society",
            "6. Bhakti-Sufi Traditions: Changes in Religious Beliefs",
            "7. An Imperial Capital: Vijayanagara",
            "8. Peasants, Zamindars and the State: Agrarian Society",
            "9. Kings and Chronicles: The Mughal Courts",
            "10. Colonialism and the Countryside: Exploring Official Archives",
            "11. Rebels and the Raj: The Revolt of 1857 and its Representations",
            "12. Colonial Cities: Urbanisation, Planning and Architecture",
            "13. Mahatma Gandhi and the Nationalist Movement",
            "14. Understanding Partition",
            "15. Framing the Constitution: The Beginning of a New Era"
        ],
        "Geography": [
            "1. Human Geography: Nature and Scope",
            "2. The World Population: Distribution, Density and Growth",
            "3. Human Development",
            "4. Primary Activities",
            "5. Secondary Activities",
            "6. Tertiary and Quaternary Activities",
            "7. Transport and Communication",
            "8. International Trade",
            "9. Human Settlements"
        ],
        "Political Science": [
            "1. The Cold War Era",
            "2. The End of Bipolarity",
            "3. US Hegemony in World Politics",
            "4. Alternative Centres of Power",
            "5. Contemporary South Asia",
            "6. International Organisations",
            "7. Security in the Contemporary World",
            "8. Environment and Natural Resources",
            "9. Globalisation",
            "10. Challenges of Nation Building",
            "11. Era of One-Party Dominance",
            "12. Politics of Planned Development",
            "13. India's External Relations",
            "14. Challenges to and Restoration of the Congress System",
            "15. Crisis of Democratic Order",
            "16. Rise of Popular Movements",
            "17. Regional Aspirations",
            "18. Democratic Resurgence"
        ],
        "Economics": [
            "1. Indian Economy on the Eve of Independence",
            "2. Indian Economy 1950-1990",
            "3. Liberalisation, Privatisation and Globalisation: An Appraisal",
            "4. Poverty",
            "5. Human Capital Formation in India",
            "6. Rural Development",
            "7. Employment: Growth, Informalisation and Other Issues",
            "8. Infrastructure",
            "9. Environment and Sustainable Development",
            "10. Comparative Development Experiences of India and its Neighbours"
        ],
        "Computer Science": [
            "1. Computer Fundamentals",
            "2. Boolean Algebra",
            "3. Database Concepts",
            "4. SQL",
            "5. Introduction to Web Technology",
            "6. Web Page Designing",
            "7. Web Services",
            "8. Web Scripting",
            "9. Web Application Development",
            "10. Mobile Applications"
        ]
    }
};
